import { Emotion } from "./interface";

const emotion: Array<Emotion> = [{ id: 0, emotion: '微笑', }, { id: 1, emotion: '撇嘴', }, { id: 2, emotion: '色', }, { id: 3, emotion: '发呆', }, { id: 4, emotion: '得意', }, { id: 5, emotion: '流泪', }, { id: 6, emotion: '害羞', }, { id: 7, emotion: '闭嘴', }, { id: 8, emotion: '睡', }, { id: 9, emotion: '大哭', },
{ id: 10, emotion: '尴尬', }, { id: 11, emotion: '发怒', }, { id: 12, emotion: '调皮', }, { id: 13, emotion: '呲牙', }, { id: 14, emotion: '惊讶', }, { id: 15, emotion: '难过', }, { id: 16, emotion: '酷', }, { id: 17, emotion: '冷汗', }, { id: 18, emotion: '抓狂', }, { id: 19, emotion: '吐', }, { id: 20, emotion: '偷笑', },
{ id: 21, emotion: '可爱', }, { id: 22, emotion: '白眼', }, { id: 23, emotion: '傲慢', }, { id: 24, emotion: '饥饿', }, { id: 25, emotion: '困', }, { id: 26, emotion: '惊恐', }, { id: 27, emotion: '白眼', }, { id: 28, emotion: '憨笑', }, { id: 29, emotion: '大兵', }, { id: 30, emotion: '奋斗', }, { id: 31, emotion: '咒骂', },
{ id: 32, emotion: '疑问', }, { id: 33, emotion: '嘘', }, { id: 34, emotion: '晕', }, { id: 35, emotion: '折磨', }, { id: 36, emotion: '衰', }, { id: 37, emotion: '骷髅', }, { id: 38, emotion: '敲打', }, { id: 39, emotion: '再见', }, { id: 40, emotion: '擦汗', }, { id: 41, emotion: '抠鼻', }, { id: 42, emotion: '鼓掌', },
{ id: 43, emotion: '糗大了', }, { id: 44, emotion: '坏笑', }, { id: 45, emotion: '左哼哼', }, { id: 46, emotion: '右哼哼', }, { id: 47, emotion: '哈欠', }, { id: 48, emotion: '鄙视', }, { id: 49, emotion: '委屈', }, { id: 50, emotion: '快哭了', }, { id: 51, emotion: '阴险', }, { id: 52, emotion: '亲亲', }, { id: 53, emotion: '吓', },
{ id: 54, emotion: '可怜', }, { id: 55, emotion: '菜刀', }, { id: 56, emotion: '西瓜', }, { id: 57, emotion: '啤酒', }, { id: 58, emotion: '篮球', }, { id: 59, emotion: '乒乓', }, { id: 60, emotion: '咖啡', }, { id: 61, emotion: '饭', }, { id: 62, emotion: '猪头', }, { id: 63, emotion: '玫瑰', }, { id: 64, emotion: '凋谢', },
{ id: 65, emotion: '示爱', }, { id: 66, emotion: '爱心', }, { id: 67, emotion: '心碎', }, { id: 68, emotion: '蛋糕', }, { id: 69, emotion: '闪电', }, { id: 70, emotion: '炸弹', }, { id: 71, emotion: '刀', }, { id: 72, emotion: '足球', }, { id: 73, emotion: '瓢虫', }, { id: 74, emotion: '便便', }, { id: 75, emotion: '月亮', },
{ id: 76, emotion: '太阳', }, { id: 77, emotion: '礼物', }, { id: 78, emotion: '拥抱', }, { id: 79, emotion: '强', }, { id: 80, emotion: '弱', }, { id: 81, emotion: '握手', }, { id: 82, emotion: '胜利', }, { id: 83, emotion: '抱拳', }, { id: 84, emotion: '勾引', }, { id: 85, emotion: '拳头', }, { id: 86, emotion: '差劲', },
{ id: 87, emotion: '爱你', }, { id: 88, emotion: 'NO', }, { id: 89, emotion: 'OK', }, { id: 90, emotion: '爱情', }, { id: 91, emotion: '飞吻', }, { id: 92, emotion: '跳跳', }, { id: 93, emotion: '发抖', }, { id: 94, emotion: '怄火', }, { id: 95, emotion: '转圈眼', }, { id: 96, emotion: '磕头', }, { id: 97, emotion: '回头', },
{ id: 98, emotion: '跳绳', }, { id: 99, emotion: '挥手', }, { id: 100, emotion: '激动', }, { id: 101, emotion: '街舞', }, { id: 102, emotion: '献吻', }, { id: 103, emotion: '左太极', }, { id: 104, emotion: '右太极', }];

export default emotion